name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions repo # required so we can reference the actions locally
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
            ref: nastia/ref_fix
            path: actions
            repository: duckduckgo/native-github-asana-sync

      - name: Checkout actions repo # required so we can reference the actions locally
        uses: ./actions/.github/workflows/test-workflow.yml
